parameters: {}
environment: {}
packages:
  - name: s3-image-compress
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: s3-image-compress
        binary: false
        main: ""
        runtime: nodejs:18
        web: true
        parameters: {}
        environment:
          SPACES_REGION: "${SPACES_REGION}"
          SPACES_BUCKET: "${SPACES_BUCKET}"
          SPACES_ACCESS_KEY: "${SPACES_ACCESS_KEY}"
          SPACES_SECRET_KEY: "${SPACES_SECRET_KEY}"
        annotations: {}
        limits: {}
