// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: follows.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM follows
WHERE following_id = $1 AND follower_id = $2
`

type DeleteFollowParams struct {
	FollowingID int32 `json:"followingId"`
	FollowerID  int32 `json:"followerId"`
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.Exec(ctx, deleteFollow, arg.FollowingID, arg.FollowerID)
	return err
}

const getFollowersByUserId = `-- name: GetFollowersByUserId :many
SELECT u.user_id, u.email, u.username, u.created_at, u.name
FROM users u
INNER JOIN follows f ON u.user_id = f.follower_id
WHERE f.following_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowersByUserIdParams struct {
	FollowingID int32 `json:"followingId"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

type GetFollowersByUserIdRow struct {
	UserID    int32            `json:"userId"`
	Email     string           `json:"email"`
	Username  string           `json:"username"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	Name      pgtype.Text      `json:"name"`
}

func (q *Queries) GetFollowersByUserId(ctx context.Context, arg GetFollowersByUserIdParams) ([]GetFollowersByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getFollowersByUserId, arg.FollowingID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowersByUserIdRow
	for rows.Next() {
		var i GetFollowersByUserIdRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Username,
			&i.CreatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingByUserId = `-- name: GetFollowingByUserId :many
SELECT u.user_id, u.email, u.username, u.created_at, u.name
FROM users u
INNER JOIN follows f ON u.user_id = f.following_id
WHERE f.follower_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowingByUserIdParams struct {
	FollowerID int32 `json:"followerId"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

type GetFollowingByUserIdRow struct {
	UserID    int32            `json:"userId"`
	Email     string           `json:"email"`
	Username  string           `json:"username"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	Name      pgtype.Text      `json:"name"`
}

func (q *Queries) GetFollowingByUserId(ctx context.Context, arg GetFollowingByUserIdParams) ([]GetFollowingByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getFollowingByUserId, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowingByUserIdRow
	for rows.Next() {
		var i GetFollowingByUserIdRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Username,
			&i.CreatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIsUserFollowingUser = `-- name: GetIsUserFollowingUser :one
SELECT EXISTS (
  SELECT 1
  FROM follows
  WHERE follower_id = $1 AND following_id = $2
)
`

type GetIsUserFollowingUserParams struct {
	FollowerID  int32 `json:"followerId"`
	FollowingID int32 `json:"followingId"`
}

func (q *Queries) GetIsUserFollowingUser(ctx context.Context, arg GetIsUserFollowingUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, getIsUserFollowingUser, arg.FollowerID, arg.FollowingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getMutualConnectionsForUser = `-- name: GetMutualConnectionsForUser :many
SELECT DISTINCT u.username
FROM users u
WHERE EXISTS (
  SELECT 1
  FROM follows f
  WHERE f.follower_id = $1
    AND following_id = u.user_id
) AND EXISTS (
  SELECT 1
  FROM follows f
  WHERE f.follower_id = $2
    AND following_id = u.user_id
)
`

type GetMutualConnectionsForUserParams struct {
	FollowerID   int32 `json:"followerId"`
	FollowerID_2 int32 `json:"followerId2"`
}

func (q *Queries) GetMutualConnectionsForUser(ctx context.Context, arg GetMutualConnectionsForUserParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getMutualConnectionsForUser, arg.FollowerID, arg.FollowerID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var username string
		if err := rows.Scan(&username); err != nil {
			return nil, err
		}
		items = append(items, username)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFollow = `-- name: InsertFollow :exec
INSERT INTO follows (follower_id, following_id)
VALUES ($1, $2)
`

type InsertFollowParams struct {
	FollowerID  int32 `json:"followerId"`
	FollowingID int32 `json:"followingId"`
}

func (q *Queries) InsertFollow(ctx context.Context, arg InsertFollowParams) error {
	_, err := q.db.Exec(ctx, insertFollow, arg.FollowerID, arg.FollowingID)
	return err
}
