// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: likes.sql

package queries

import (
	"context"
)

const addLike = `-- name: AddLike :exec
INSERT INTO likes (post_id, comment_id, user_id)
VALUES ($1, $2, $3)
`

type AddLikeParams struct {
	PostID    int  `json:"postId"`
	CommentID *int `json:"commentId"`
	UserID    int  `json:"userId"`
}

func (q *Queries) AddLike(ctx context.Context, arg AddLikeParams) error {
	_, err := q.db.Exec(ctx, addLike, arg.PostID, arg.CommentID, arg.UserID)
	return err
}

const getIsLikedByUser = `-- name: GetIsLikedByUser :one
SELECT EXISTS (
  SELECT 1
  FROM likes
  WHERE user_id = $1
  AND post_id = $2
  AND (
    CASE
      WHEN $4::boolean = FALSE THEN comment_id = $3
      ELSE comment_id IS NULL
    END
  )
)
`

type GetIsLikedByUserParams struct {
	UserID    int  `json:"userId"`
	PostID    int  `json:"postId"`
	CommentID *int `json:"commentId"`
	Column4   bool `json:"column4"`
}

func (q *Queries) GetIsLikedByUser(ctx context.Context, arg GetIsLikedByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, getIsLikedByUser,
		arg.UserID,
		arg.PostID,
		arg.CommentID,
		arg.Column4,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getIsPostLikedByUser = `-- name: GetIsPostLikedByUser :one
SELECT EXISTS (
  SELECT 1
  FROM likes
  WHERE user_id = $1
    AND post_id = $2
    AND comment_id IS NULL
)
`

type GetIsPostLikedByUserParams struct {
	UserID int `json:"userId"`
	PostID int `json:"postId"`
}

func (q *Queries) GetIsPostLikedByUser(ctx context.Context, arg GetIsPostLikedByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, getIsPostLikedByUser, arg.UserID, arg.PostID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getPostLikes = `-- name: GetPostLikes :many
SELECT users.username, users.user_id, users.is_verified
FROM likes
JOIN users ON likes.user_id = users.user_id
WHERE likes.post_id = $1
AND likes.user_id != $2
AND NOT EXISTS (
    SELECT 1 FROM block
    WHERE block.user_id = $2
        AND likes.user_id = block.target_user_id
) AND NOT EXISTS (
    SELECT 1 FROM block
    WHERE block.user_id = likes.user_id
        AND block.target_user_id = $2
)
LIMIT 3
`

type GetPostLikesParams struct {
	PostID int `json:"postId"`
	UserID int `json:"userId"`
}

type GetPostLikesRow struct {
	Username   string `json:"username"`
	UserID     int    `json:"userId"`
	IsVerified bool   `json:"isVerified"`
}

func (q *Queries) GetPostLikes(ctx context.Context, arg GetPostLikesParams) ([]GetPostLikesRow, error) {
	rows, err := q.db.Query(ctx, getPostLikes, arg.PostID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostLikesRow
	for rows.Next() {
		var i GetPostLikesRow
		if err := rows.Scan(&i.Username, &i.UserID, &i.IsVerified); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLike = `-- name: RemoveLike :exec
DELETE FROM likes
WHERE post_id = $1
AND user_id = $2
AND ($3 = TRUE OR comment_id = $4)
`

type RemoveLikeParams struct {
	PostID    int         `json:"postId"`
	UserID    int         `json:"userId"`
	Column3   interface{} `json:"column3"`
	CommentID *int        `json:"commentId"`
}

func (q *Queries) RemoveLike(ctx context.Context, arg RemoveLikeParams) error {
	_, err := q.db.Exec(ctx, removeLike,
		arg.PostID,
		arg.UserID,
		arg.Column3,
		arg.CommentID,
	)
	return err
}
