// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notifications.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	db "splajompy.com/api/v2/internal/db"
)

const deleteNotificationById = `-- name: DeleteNotificationById :exec
DELETE FROM notifications 
WHERE notification_id = $1
`

func (q *Queries) DeleteNotificationById(ctx context.Context, notificationID int32) error {
	_, err := q.db.Exec(ctx, deleteNotificationById, notificationID)
	return err
}

const findUnreadLikeNotification = `-- name: FindUnreadLikeNotification :one
SELECT notification_id, user_id, post_id, comment_id, message, link, viewed, facets, notification_type, created_at
FROM notifications 
WHERE user_id = $1 
  AND notification_type = 'like'
  AND viewed = FALSE
  AND (($2::int IS NULL AND post_id = $3 AND comment_id IS NULL) OR 
       ($2::int IS NOT NULL AND post_id = $3 AND comment_id = $2))
ORDER BY created_at DESC
LIMIT 1
`

type FindUnreadLikeNotificationParams struct {
	UserID  int32       `json:"userId"`
	Column2 int32       `json:"column2"`
	PostID  pgtype.Int4 `json:"postId"`
}

func (q *Queries) FindUnreadLikeNotification(ctx context.Context, arg FindUnreadLikeNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, findUnreadLikeNotification, arg.UserID, arg.Column2, arg.PostID)
	var i Notification
	err := row.Scan(
		&i.NotificationID,
		&i.UserID,
		&i.PostID,
		&i.CommentID,
		&i.Message,
		&i.Link,
		&i.Viewed,
		&i.Facets,
		&i.NotificationType,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationById = `-- name: GetNotificationById :one
SELECT notification_id, user_id, post_id, comment_id, message, link, viewed, facets, notification_type, created_at
FROM notifications
WHERE notification_id = $1
LIMIT 1
`

func (q *Queries) GetNotificationById(ctx context.Context, notificationID int32) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationById, notificationID)
	var i Notification
	err := row.Scan(
		&i.NotificationID,
		&i.UserID,
		&i.PostID,
		&i.CommentID,
		&i.Message,
		&i.Link,
		&i.Viewed,
		&i.Facets,
		&i.NotificationType,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationsForUserId = `-- name: GetNotificationsForUserId :many
SELECT notification_id, user_id, post_id, comment_id, message, link, viewed, facets, notification_type, created_at
FROM notifications 
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type GetNotificationsForUserIdParams struct {
	UserID int32 `json:"userId"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetNotificationsForUserId(ctx context.Context, arg GetNotificationsForUserIdParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsForUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotificationID,
			&i.UserID,
			&i.PostID,
			&i.CommentID,
			&i.Message,
			&i.Link,
			&i.Viewed,
			&i.Facets,
			&i.NotificationType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReadNotificationsForUserIdWithTimeOffset = `-- name: GetReadNotificationsForUserIdWithTimeOffset :many
SELECT notification_id, user_id, post_id, comment_id, message, link, viewed, facets, notification_type, created_at
FROM notifications 
WHERE user_id = $1 AND viewed = TRUE AND created_at < $2
ORDER BY created_at DESC
LIMIT $3
`

type GetReadNotificationsForUserIdWithTimeOffsetParams struct {
	UserID    int32            `json:"userId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	Limit     int32            `json:"limit"`
}

func (q *Queries) GetReadNotificationsForUserIdWithTimeOffset(ctx context.Context, arg GetReadNotificationsForUserIdWithTimeOffsetParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getReadNotificationsForUserIdWithTimeOffset, arg.UserID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotificationID,
			&i.UserID,
			&i.PostID,
			&i.CommentID,
			&i.Message,
			&i.Link,
			&i.Viewed,
			&i.Facets,
			&i.NotificationType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationsForUserId = `-- name: GetUnreadNotificationsForUserId :many
SELECT notification_id, user_id, post_id, comment_id, message, link, viewed, facets, notification_type, created_at
FROM notifications 
WHERE user_id = $1 AND viewed = FALSE
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type GetUnreadNotificationsForUserIdParams struct {
	UserID int32 `json:"userId"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetUnreadNotificationsForUserId(ctx context.Context, arg GetUnreadNotificationsForUserIdParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getUnreadNotificationsForUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotificationID,
			&i.UserID,
			&i.PostID,
			&i.CommentID,
			&i.Message,
			&i.Link,
			&i.Viewed,
			&i.Facets,
			&i.NotificationType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationsForUserIdWithTimeOffset = `-- name: GetUnreadNotificationsForUserIdWithTimeOffset :many
SELECT notification_id, user_id, post_id, comment_id, message, link, viewed, facets, notification_type, created_at
FROM notifications 
WHERE user_id = $1 AND viewed = FALSE AND created_at < $2
ORDER BY created_at DESC
LIMIT $3
`

type GetUnreadNotificationsForUserIdWithTimeOffsetParams struct {
	UserID    int32            `json:"userId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	Limit     int32            `json:"limit"`
}

func (q *Queries) GetUnreadNotificationsForUserIdWithTimeOffset(ctx context.Context, arg GetUnreadNotificationsForUserIdWithTimeOffsetParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getUnreadNotificationsForUserIdWithTimeOffset, arg.UserID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotificationID,
			&i.UserID,
			&i.PostID,
			&i.CommentID,
			&i.Message,
			&i.Link,
			&i.Viewed,
			&i.Facets,
			&i.NotificationType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserUnreadNotificationCount = `-- name: GetUserUnreadNotificationCount :one
SELECT COUNT(*)
FROM notifications
WHERE user_id = $1 AND viewed = FALSE
`

func (q *Queries) GetUserUnreadNotificationCount(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getUserUnreadNotificationCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifications (user_id, post_id, comment_id, message, facets, link, notification_type)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertNotificationParams struct {
	UserID           int32       `json:"userId"`
	PostID           pgtype.Int4 `json:"postId"`
	CommentID        pgtype.Int4 `json:"commentId"`
	Message          string      `json:"message"`
	Facets           db.Facets   `json:"facets"`
	Link             pgtype.Text `json:"link"`
	NotificationType string      `json:"notificationType"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.UserID,
		arg.PostID,
		arg.CommentID,
		arg.Message,
		arg.Facets,
		arg.Link,
		arg.NotificationType,
	)
	return err
}

const markAllNotificationsAsReadForUser = `-- name: MarkAllNotificationsAsReadForUser :exec
UPDATE notifications
SET viewed = TRUE
WHERE user_id = $1
`

func (q *Queries) MarkAllNotificationsAsReadForUser(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, markAllNotificationsAsReadForUser, userID)
	return err
}

const markNotificationAsReadById = `-- name: MarkNotificationAsReadById :exec
UPDATE notifications
SET viewed = TRUE
WHERE notification_id = $1
`

func (q *Queries) MarkNotificationAsReadById(ctx context.Context, notificationID int32) error {
	_, err := q.db.Exec(ctx, markNotificationAsReadById, notificationID)
	return err
}

const userHasUnreadNotifications = `-- name: UserHasUnreadNotifications :one
SELECT EXISTS (
  SELECT 1
  FROM notifications
  WHERE user_id = $1 AND viewed = FALSE
)
`

func (q *Queries) UserHasUnreadNotifications(ctx context.Context, userID int32) (bool, error) {
	row := q.db.QueryRow(ctx, userHasUnreadNotifications, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
