// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	db "splajompy.com/api/v2/internal/db"
)

const deleteNotificationById = `-- name: DeleteNotificationById :exec
DELETE FROM notifications
WHERE notification_id = $1
`

func (q *Queries) DeleteNotificationById(ctx context.Context, notificationID int) error {
	_, err := q.db.Exec(ctx, deleteNotificationById, notificationID)
	return err
}

const findUnreadLikeNotificationForComment = `-- name: FindUnreadLikeNotificationForComment :one
SELECT notification_id, user_id, post_id, comment_id, target_user_id, message, link, viewed, facets, notification_type, created_at
FROM notifications
WHERE user_id = $1
  AND notification_type = 'like'
  AND viewed = FALSE
  AND post_id = $2
  AND comment_id = $3
ORDER BY created_at DESC
LIMIT 1
`

type FindUnreadLikeNotificationForCommentParams struct {
	UserID    int  `json:"userId"`
	PostID    *int `json:"postId"`
	CommentID *int `json:"commentId"`
}

func (q *Queries) FindUnreadLikeNotificationForComment(ctx context.Context, arg FindUnreadLikeNotificationForCommentParams) (Notification, error) {
	row := q.db.QueryRow(ctx, findUnreadLikeNotificationForComment, arg.UserID, arg.PostID, arg.CommentID)
	var i Notification
	err := row.Scan(
		&i.NotificationID,
		&i.UserID,
		&i.PostID,
		&i.CommentID,
		&i.TargetUserID,
		&i.Message,
		&i.Link,
		&i.Viewed,
		&i.Facets,
		&i.NotificationType,
		&i.CreatedAt,
	)
	return i, err
}

const findUnreadLikeNotificationForPost = `-- name: FindUnreadLikeNotificationForPost :one
SELECT notification_id, user_id, post_id, comment_id, target_user_id, message, link, viewed, facets, notification_type, created_at
FROM notifications
WHERE user_id = $1
  AND notification_type = 'like'
  AND viewed = FALSE
  AND post_id = $2
  AND comment_id IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type FindUnreadLikeNotificationForPostParams struct {
	UserID int  `json:"userId"`
	PostID *int `json:"postId"`
}

func (q *Queries) FindUnreadLikeNotificationForPost(ctx context.Context, arg FindUnreadLikeNotificationForPostParams) (Notification, error) {
	row := q.db.QueryRow(ctx, findUnreadLikeNotificationForPost, arg.UserID, arg.PostID)
	var i Notification
	err := row.Scan(
		&i.NotificationID,
		&i.UserID,
		&i.PostID,
		&i.CommentID,
		&i.TargetUserID,
		&i.Message,
		&i.Link,
		&i.Viewed,
		&i.Facets,
		&i.NotificationType,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationActors = `-- name: GetNotificationActors :many
SELECT user_id
FROM notification_actor
WHERE notification_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetNotificationActors(ctx context.Context, notificationID int) ([]int, error) {
	rows, err := q.db.Query(ctx, getNotificationActors, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int
	for rows.Next() {
		var user_id int
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationById = `-- name: GetNotificationById :one
SELECT notification_id, user_id, post_id, comment_id, target_user_id, message, link, viewed, facets, notification_type, created_at
FROM notifications
WHERE notification_id = $1
LIMIT 1
`

func (q *Queries) GetNotificationById(ctx context.Context, notificationID int) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationById, notificationID)
	var i Notification
	err := row.Scan(
		&i.NotificationID,
		&i.UserID,
		&i.PostID,
		&i.CommentID,
		&i.TargetUserID,
		&i.Message,
		&i.Link,
		&i.Viewed,
		&i.Facets,
		&i.NotificationType,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationsForUserId = `-- name: GetNotificationsForUserId :many
SELECT notification_id, user_id, post_id, comment_id, target_user_id, message, link, viewed, facets, notification_type, created_at
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type GetNotificationsForUserIdParams struct {
	UserID int `json:"userId"`
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}

func (q *Queries) GetNotificationsForUserId(ctx context.Context, arg GetNotificationsForUserIdParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsForUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotificationID,
			&i.UserID,
			&i.PostID,
			&i.CommentID,
			&i.TargetUserID,
			&i.Message,
			&i.Link,
			&i.Viewed,
			&i.Facets,
			&i.NotificationType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsForUserIdWithTimeOffset = `-- name: GetNotificationsForUserIdWithTimeOffset :many
SELECT notifications.notification_id, notifications.user_id, notifications.post_id, notifications.comment_id, notifications.target_user_id, notifications.message, notifications.link, notifications.viewed, notifications.facets, notifications.notification_type, notifications.created_at
FROM notifications
LEFT JOIN posts ON notifications.post_id = posts.post_id
WHERE notifications.user_id = $1 AND notifications.viewed = $4 AND notifications.created_at < $2
    AND (
        $5::text IS NULL
            OR notifications.notification_type = $5
    ) AND NOT EXISTS ( -- no notifications targeting blocked users
        SELECT 1 FROM block
        WHERE block.user_id = $1
            AND block.target_user_id = notifications.target_user_id
    ) AND NOT EXISTS ( -- no notifications referencing posts from blocked users
        SELECT 1 FROM block
        JOIN posts ON posts.post_id = notifications.post_id
        WHERE block.user_id = $1
            AND posts.user_id = block.target_user_id
    ) AND NOT EXISTS ( -- no notifications refering posts from users that have blocked this user
        SELECT 1 FROM block
        JOIN posts ON posts.post_id = notifications.post_id
        WHERE block.user_id = posts.user_id
            AND block.target_user_id = $1
    ) AND (
        notifications.post_id IS NULL
        OR posts.visibilityType = 0 -- public
        OR posts.user_id = $1
        OR EXISTS (
            SELECT 1
            FROM user_relationship
            WHERE user_id = posts.user_id
                AND target_user_id = $1
                AND user_relationship.created_at < posts.created_at
        )
    )
ORDER BY notifications.created_at DESC
LIMIT $3
`

type GetNotificationsForUserIdWithTimeOffsetParams struct {
	UserID           int              `json:"userId"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	Limit            int              `json:"limit"`
	Viewed           bool             `json:"viewed"`
	NotificationType pgtype.Text      `json:"notificationType"`
}

func (q *Queries) GetNotificationsForUserIdWithTimeOffset(ctx context.Context, arg GetNotificationsForUserIdWithTimeOffsetParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsForUserIdWithTimeOffset,
		arg.UserID,
		arg.CreatedAt,
		arg.Limit,
		arg.Viewed,
		arg.NotificationType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotificationID,
			&i.UserID,
			&i.PostID,
			&i.CommentID,
			&i.TargetUserID,
			&i.Message,
			&i.Link,
			&i.Viewed,
			&i.Facets,
			&i.NotificationType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationsForUserId = `-- name: GetUnreadNotificationsForUserId :many
SELECT notification_id, user_id, post_id, comment_id, target_user_id, message, link, viewed, facets, notification_type, created_at
FROM notifications
WHERE user_id = $1 AND viewed = FALSE
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type GetUnreadNotificationsForUserIdParams struct {
	UserID int `json:"userId"`
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}

func (q *Queries) GetUnreadNotificationsForUserId(ctx context.Context, arg GetUnreadNotificationsForUserIdParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getUnreadNotificationsForUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotificationID,
			&i.UserID,
			&i.PostID,
			&i.CommentID,
			&i.TargetUserID,
			&i.Message,
			&i.Link,
			&i.Viewed,
			&i.Facets,
			&i.NotificationType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserUnreadNotificationCount = `-- name: GetUserUnreadNotificationCount :one
SELECT COUNT(*)
FROM notifications
WHERE user_id = $1 AND viewed = FALSE
`

func (q *Queries) GetUserUnreadNotificationCount(ctx context.Context, userID int) (int64, error) {
	row := q.db.QueryRow(ctx, getUserUnreadNotificationCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (user_id, post_id, comment_id, message, facets, link, notification_type, target_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING notification_id, user_id, post_id, comment_id, target_user_id, message, link, viewed, facets, notification_type, created_at
`

type InsertNotificationParams struct {
	UserID           int         `json:"userId"`
	PostID           *int        `json:"postId"`
	CommentID        *int        `json:"commentId"`
	Message          string      `json:"message"`
	Facets           db.Facets   `json:"facets"`
	Link             pgtype.Text `json:"link"`
	NotificationType string      `json:"notificationType"`
	TargetUserID     *int        `json:"targetUserId"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.UserID,
		arg.PostID,
		arg.CommentID,
		arg.Message,
		arg.Facets,
		arg.Link,
		arg.NotificationType,
		arg.TargetUserID,
	)
	var i Notification
	err := row.Scan(
		&i.NotificationID,
		&i.UserID,
		&i.PostID,
		&i.CommentID,
		&i.TargetUserID,
		&i.Message,
		&i.Link,
		&i.Viewed,
		&i.Facets,
		&i.NotificationType,
		&i.CreatedAt,
	)
	return i, err
}

const insertNotificationActor = `-- name: InsertNotificationActor :exec
INSERT INTO notification_actor (notification_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertNotificationActorParams struct {
	NotificationID int `json:"notificationId"`
	UserID         int `json:"userId"`
}

func (q *Queries) InsertNotificationActor(ctx context.Context, arg InsertNotificationActorParams) error {
	_, err := q.db.Exec(ctx, insertNotificationActor, arg.NotificationID, arg.UserID)
	return err
}

const markAllNotificationsAsReadForUser = `-- name: MarkAllNotificationsAsReadForUser :exec
UPDATE notifications
SET viewed = TRUE
WHERE user_id = $1
`

func (q *Queries) MarkAllNotificationsAsReadForUser(ctx context.Context, userID int) error {
	_, err := q.db.Exec(ctx, markAllNotificationsAsReadForUser, userID)
	return err
}

const markNotificationAsReadById = `-- name: MarkNotificationAsReadById :exec
UPDATE notifications
SET viewed = TRUE
WHERE notification_id = $1
`

func (q *Queries) MarkNotificationAsReadById(ctx context.Context, notificationID int) error {
	_, err := q.db.Exec(ctx, markNotificationAsReadById, notificationID)
	return err
}

const updateNotificationMessage = `-- name: UpdateNotificationMessage :exec
UPDATE notifications
SET message = $2
WHERE notification_id = $1
`

type UpdateNotificationMessageParams struct {
	NotificationID int    `json:"notificationId"`
	Message        string `json:"message"`
}

func (q *Queries) UpdateNotificationMessage(ctx context.Context, arg UpdateNotificationMessageParams) error {
	_, err := q.db.Exec(ctx, updateNotificationMessage, arg.NotificationID, arg.Message)
	return err
}

const userHasUnreadNotifications = `-- name: UserHasUnreadNotifications :one
SELECT EXISTS (
  SELECT 1
  FROM notifications
  WHERE user_id = $1 AND viewed = FALSE
)
`

func (q *Queries) UserHasUnreadNotifications(ctx context.Context, userID int) (bool, error) {
	row := q.db.QueryRow(ctx, userHasUnreadNotifications, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
