// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	db "splajompy.com/api/v2/internal/db"
)

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE post_id = $1
`

func (q *Queries) DeletePost(ctx context.Context, postID int) error {
	_, err := q.db.Exec(ctx, deletePost, postID)
	return err
}

const getAllImagesByUserId = `-- name: GetAllImagesByUserId :many
SELECT images.image_id, images.height, images.width, images.image_blob_url
FROM images
JOIN post_images ON images.image_id = post_images.image_id
JOIN posts ON posts.post_id = post_images.post_id
WHERE posts.user_id = $1
`

func (q *Queries) GetAllImagesByUserId(ctx context.Context, userID int) ([]Image, error) {
	rows, err := q.db.Query(ctx, getAllImagesByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ImageID,
			&i.Height,
			&i.Width,
			&i.ImageBlobUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentCountByPostID = `-- name: GetCommentCountByPostID :one
SELECT COUNT(*)
FROM comments
WHERE post_id = $1
`

func (q *Queries) GetCommentCountByPostID(ctx context.Context, postID int) (int64, error) {
	row := q.db.QueryRow(ctx, getCommentCountByPostID, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getImagesByPostId = `-- name: GetImagesByPostId :many
SELECT images.image_id, images.height, images.width, images.image_blob_url
FROM images
JOIN post_images ON images.image_id = post_images.image_id
WHERE post_images.post_id = $1
ORDER BY post_images.display_order ASC
`

func (q *Queries) GetImagesByPostId(ctx context.Context, postID int) ([]Image, error) {
	rows, err := q.db.Query(ctx, getImagesByPostId, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ImageID,
			&i.Height,
			&i.Width,
			&i.ImageBlobUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPinnedPostId = `-- name: GetPinnedPostId :one
SELECT pinned_post_id
FROM users
WHERE user_id = $1
`

func (q *Queries) GetPinnedPostId(ctx context.Context, userID int) (*int, error) {
	row := q.db.QueryRow(ctx, getPinnedPostId, userID)
	var pinned_post_id *int
	err := row.Scan(&pinned_post_id)
	return pinned_post_id, err
}

const getPollVotesGrouped = `-- name: GetPollVotesGrouped :many
SELECT option_index, COUNT(*) AS count
FROM poll_vote
WHERE post_id = $1
GROUP BY option_index
`

type GetPollVotesGroupedRow struct {
	OptionIndex int   `json:"optionIndex"`
	Count       int64 `json:"count"`
}

func (q *Queries) GetPollVotesGrouped(ctx context.Context, postID int) ([]GetPollVotesGroupedRow, error) {
	rows, err := q.db.Query(ctx, getPollVotesGrouped, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPollVotesGroupedRow
	for rows.Next() {
		var i GetPollVotesGroupedRow
		if err := rows.Scan(&i.OptionIndex, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserVoteInPoll = `-- name: GetUserVoteInPoll :one
SELECT option_index
FROM poll_vote
WHERE post_id = $1 AND user_id = $2
`

type GetUserVoteInPollParams struct {
	PostID int `json:"postId"`
	UserID int `json:"userId"`
}

func (q *Queries) GetUserVoteInPoll(ctx context.Context, arg GetUserVoteInPollParams) (int, error) {
	row := q.db.QueryRow(ctx, getUserVoteInPoll, arg.PostID, arg.UserID)
	var option_index int
	err := row.Scan(&option_index)
	return option_index, err
}

const insertImage = `-- name: InsertImage :one
INSERT INTO images (height, width, image_blob_url)
VALUES ($1, $2, $3)
RETURNING image_id, height, width, image_blob_url
`

type InsertImageParams struct {
	Height       int    `json:"height"`
	Width        int    `json:"width"`
	ImageBlobUrl string `json:"imageBlobUrl"`
}

func (q *Queries) InsertImage(ctx context.Context, arg InsertImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, insertImage, arg.Height, arg.Width, arg.ImageBlobUrl)
	var i Image
	err := row.Scan(
		&i.ImageID,
		&i.Height,
		&i.Width,
		&i.ImageBlobUrl,
	)
	return i, err
}

const insertPost = `-- name: InsertPost :one
INSERT INTO posts (user_id, text, facets, attributes, visibilityType)
VALUES ($1, $2, $3, $4, $5)
RETURNING post_id, user_id, text, created_at, facets, attributes, visibilitytype
`

type InsertPostParams struct {
	UserID         int            `json:"userId"`
	Text           pgtype.Text    `json:"text"`
	Facets         db.Facets      `json:"facets"`
	Attributes     *db.Attributes `json:"attributes"`
	Visibilitytype int            `json:"visibilitytype"`
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, insertPost,
		arg.UserID,
		arg.Text,
		arg.Facets,
		arg.Attributes,
		arg.Visibilitytype,
	)
	var i Post
	err := row.Scan(
		&i.PostID,
		&i.UserID,
		&i.Text,
		&i.CreatedAt,
		&i.Facets,
		&i.Attributes,
		&i.Visibilitytype,
	)
	return i, err
}

const insertPostImage = `-- name: InsertPostImage :exec
INSERT INTO post_images (post_id, image_id, display_order)
VALUES ($1, $2, $3)
`

type InsertPostImageParams struct {
	PostID       int `json:"postId"`
	ImageID      int `json:"imageId"`
	DisplayOrder int `json:"displayOrder"`
}

func (q *Queries) InsertPostImage(ctx context.Context, arg InsertPostImageParams) error {
	_, err := q.db.Exec(ctx, insertPostImage, arg.PostID, arg.ImageID, arg.DisplayOrder)
	return err
}

const insertVote = `-- name: InsertVote :exec
INSERT INTO poll_vote (post_id, user_id, option_index)
VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type InsertVoteParams struct {
	PostID      int `json:"postId"`
	UserID      int `json:"userId"`
	OptionIndex int `json:"optionIndex"`
}

func (q *Queries) InsertVote(ctx context.Context, arg InsertVoteParams) error {
	_, err := q.db.Exec(ctx, insertVote, arg.PostID, arg.UserID, arg.OptionIndex)
	return err
}

const pinPost = `-- name: PinPost :exec
UPDATE users
SET pinned_post_id = $2
WHERE user_id = $1
`

type PinPostParams struct {
	UserID       int  `json:"userId"`
	PinnedPostID *int `json:"pinnedPostId"`
}

func (q *Queries) PinPost(ctx context.Context, arg PinPostParams) error {
	_, err := q.db.Exec(ctx, pinPost, arg.UserID, arg.PinnedPostID)
	return err
}

const unpinPost = `-- name: UnpinPost :exec
UPDATE users
SET pinned_post_id = NULL
WHERE user_id = $1
`

func (q *Queries) UnpinPost(ctx context.Context, userID int) error {
	_, err := q.db.Exec(ctx, unpinPost, userID)
	return err
}
