// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"
)

type Querier interface {
	AddCommentToPost(ctx context.Context, arg AddCommentToPostParams) (Comment, error)
	AddLike(ctx context.Context, arg AddLikeParams) error
	BlockUser(ctx context.Context, arg BlockUserParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) error
	DeleteComment(ctx context.Context, commentID int) error
	DeleteFollow(ctx context.Context, arg DeleteFollowParams) error
	DeleteNotificationById(ctx context.Context, notificationID int) error
	DeletePost(ctx context.Context, postID int) error
	DeleteSession(ctx context.Context, id string) error
	DeleteUserById(ctx context.Context, userID int) error
	FindUnreadLikeNotificationForComment(ctx context.Context, arg FindUnreadLikeNotificationForCommentParams) (Notification, error)
	FindUnreadLikeNotificationForPost(ctx context.Context, arg FindUnreadLikeNotificationForPostParams) (Notification, error)
	GetAllImagesByUserId(ctx context.Context, userID int) ([]Image, error)
	GetAllPostIds(ctx context.Context, arg GetAllPostIdsParams) ([]int, error)
	GetAllPostIdsCursor(ctx context.Context, arg GetAllPostIdsCursorParams) ([]int, error)
	GetBioByUserId(ctx context.Context, userID int) (string, error)
	GetCommentById(ctx context.Context, commentID int) (Comment, error)
	GetCommentCountByPostID(ctx context.Context, postID int) (int64, error)
	GetCommentsByPostId(ctx context.Context, postID int) ([]GetCommentsByPostIdRow, error)
	GetFollowersByUserId(ctx context.Context, arg GetFollowersByUserIdParams) ([]GetFollowersByUserIdRow, error)
	GetFollowingByUserId(ctx context.Context, arg GetFollowingByUserIdParams) ([]GetFollowingByUserIdRow, error)
	GetImagesByPostId(ctx context.Context, postID int) ([]Image, error)
	GetIsEmailInUse(ctx context.Context, email string) (bool, error)
	GetIsLikedByUser(ctx context.Context, arg GetIsLikedByUserParams) (bool, error)
	GetIsPostLikedByUser(ctx context.Context, arg GetIsPostLikedByUserParams) (bool, error)
	GetIsUserBlockingUser(ctx context.Context, arg GetIsUserBlockingUserParams) (bool, error)
	GetIsUserFollowingUser(ctx context.Context, arg GetIsUserFollowingUserParams) (bool, error)
	GetIsUsernameInUse(ctx context.Context, username string) (bool, error)
	GetMutualConnectionsForUser(ctx context.Context, arg GetMutualConnectionsForUserParams) ([]string, error)
	GetMutualsByUserId(ctx context.Context, arg GetMutualsByUserIdParams) ([]GetMutualsByUserIdRow, error)
	GetNotificationById(ctx context.Context, notificationID int) (Notification, error)
	GetNotificationsForUserId(ctx context.Context, arg GetNotificationsForUserIdParams) ([]Notification, error)
	GetPinnedPostId(ctx context.Context, userID int) (*int, error)
	GetPollVotesGrouped(ctx context.Context, postID int) ([]GetPollVotesGroupedRow, error)
	GetPostById(ctx context.Context, postID int) (Post, error)
	GetPostIdsByFollowing(ctx context.Context, arg GetPostIdsByFollowingParams) ([]int, error)
	GetPostIdsByFollowingCursor(ctx context.Context, arg GetPostIdsByFollowingCursorParams) ([]int, error)
	GetPostIdsByUserIdCursor(ctx context.Context, arg GetPostIdsByUserIdCursorParams) ([]int, error)
	GetPostIdsForMutualFeed(ctx context.Context, arg GetPostIdsForMutualFeedParams) ([]GetPostIdsForMutualFeedRow, error)
	GetPostIdsForMutualFeedCursor(ctx context.Context, arg GetPostIdsForMutualFeedCursorParams) ([]GetPostIdsForMutualFeedCursorRow, error)
	GetPostLikesFromFollowers(ctx context.Context, arg GetPostLikesFromFollowersParams) ([]GetPostLikesFromFollowersRow, error)
	GetPostsIdsByUserId(ctx context.Context, arg GetPostsIdsByUserIdParams) ([]int, error)
	GetReadNotificationsForUserIdWithTimeOffset(ctx context.Context, arg GetReadNotificationsForUserIdWithTimeOffsetParams) ([]Notification, error)
	GetSessionById(ctx context.Context, id string) (Session, error)
	GetTotalComments(ctx context.Context) (int64, error)
	GetTotalFollows(ctx context.Context) (int64, error)
	GetTotalLikes(ctx context.Context) (int64, error)
	GetTotalNotifications(ctx context.Context) (int64, error)
	GetTotalPosts(ctx context.Context) (int64, error)
	GetTotalUsers(ctx context.Context) (int64, error)
	GetUnreadNotificationsForUserId(ctx context.Context, arg GetUnreadNotificationsForUserIdParams) ([]Notification, error)
	GetUnreadNotificationsForUserIdWithTimeOffset(ctx context.Context, arg GetUnreadNotificationsForUserIdWithTimeOffsetParams) ([]Notification, error)
	GetUserById(ctx context.Context, userID int) (User, error)
	GetUserByIdentifier(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserUnreadNotificationCount(ctx context.Context, userID int) (int64, error)
	GetUserVoteInPoll(ctx context.Context, arg GetUserVoteInPollParams) (int, error)
	GetUserWithPasswordById(ctx context.Context, userID int) (User, error)
	GetUserWithPasswordByIdentifier(ctx context.Context, email string) (User, error)
	GetUsernameLike(ctx context.Context, arg GetUsernameLikeParams) ([]User, error)
	GetVerificationCode(ctx context.Context, arg GetVerificationCodeParams) (VerificationCode, error)
	HasLikesFromOthers(ctx context.Context, arg HasLikesFromOthersParams) (bool, error)
	InsertFollow(ctx context.Context, arg InsertFollowParams) error
	InsertImage(ctx context.Context, arg InsertImageParams) (Image, error)
	InsertNotification(ctx context.Context, arg InsertNotificationParams) error
	InsertPost(ctx context.Context, arg InsertPostParams) (Post, error)
	InsertVote(ctx context.Context, arg InsertVoteParams) error
	MarkAllNotificationsAsReadForUser(ctx context.Context, userID int) error
	MarkNotificationAsReadById(ctx context.Context, notificationID int) error
	PinPost(ctx context.Context, arg PinPostParams) error
	RemoveLike(ctx context.Context, arg RemoveLikeParams) error
	UnblockUser(ctx context.Context, arg UnblockUserParams) error
	UnpinPost(ctx context.Context, userID int) error
	UpdateSessionExpiry(ctx context.Context, arg UpdateSessionExpiryParams) error
	UpdateUserBio(ctx context.Context, arg UpdateUserBioParams) error
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error
	UserHasUnreadNotifications(ctx context.Context, userID int) (bool, error)
	UserSearchWithHeuristics(ctx context.Context, arg UserSearchWithHeuristicsParams) ([]UserSearchWithHeuristicsRow, error)
}

var _ Querier = (*Queries)(nil)
