// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: follows.sql

package db

import (
	"context"
)

const getIsUserFollowingUser = `-- name: GetIsUserFollowingUser :one
SELECT EXISTS (
  SELECT 1
  FROM follows
  WHERE follower_id = $1 AND following_id = $2
)
`

type GetIsUserFollowingUserParams struct {
	FollowerID  int32
	FollowingID int32
}

func (q *Queries) GetIsUserFollowingUser(ctx context.Context, arg GetIsUserFollowingUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, getIsUserFollowingUser, arg.FollowerID, arg.FollowingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
