// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bio struct {
	ID     int32
	UserID int32
	Text   string
}

type Comment struct {
	CommentID int32
	PostID    int32
	UserID    int32
	Text      string
	CreatedAt pgtype.Timestamp
}

type Follow struct {
	FollowerID  int32
	FollowingID int32
	CreatedAt   pgtype.Timestamp
}

type Image struct {
	ImageID      int32
	PostID       int32
	Height       int32
	Width        int32
	ImageBlobUrl string
	DisplayOrder int32
}

type Like struct {
	PostID    int32
	CommentID pgtype.Int4
	UserID    int32
	IsPost    bool
}

type Post struct {
	PostID    int32
	UserID    int32
	Text      pgtype.Text
	CreatedAt pgtype.Timestamp
}

type Session struct {
	ID        string
	UserID    int32
	ExpiresAt pgtype.Timestamp
}

type User struct {
	UserID    int32
	Email     string
	Password  string
	Username  string
	CreatedAt pgtype.Timestamp
	Name      pgtype.Text
}
