// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bio struct {
	ID     int32  `json:"id"`
	UserID int32  `json:"userId"`
	Text   string `json:"text"`
}

type Comment struct {
	CommentID int32            `json:"commentId"`
	PostID    int32            `json:"postId"`
	UserID    int32            `json:"userId"`
	Text      string           `json:"text"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type Follow struct {
	FollowerID  int32            `json:"followerId"`
	FollowingID int32            `json:"followingId"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
}

type Image struct {
	ImageID      int32  `json:"imageId"`
	PostID       int32  `json:"postId"`
	Height       int32  `json:"height"`
	Width        int32  `json:"width"`
	ImageBlobUrl string `json:"imageBlobUrl"`
	DisplayOrder int32  `json:"displayOrder"`
}

type Like struct {
	PostID    int32       `json:"postId"`
	CommentID pgtype.Int4 `json:"commentId"`
	UserID    int32       `json:"userId"`
	IsPost    bool        `json:"isPost"`
}

type Post struct {
	PostID    int32            `json:"postId"`
	UserID    int32            `json:"userId"`
	Text      pgtype.Text      `json:"text"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type Session struct {
	ID        string           `json:"id"`
	UserID    int32            `json:"userId"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

type User struct {
	UserID    int32            `json:"userId"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	Username  string           `json:"username"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	Name      pgtype.Text      `json:"name"`
}
