# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Astro Build
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
     - 'web/**'

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
    - uses: actions/checkout@v7
    - name: Use Node.js 24
      uses: actions/setup-node@v7
      with:
        node-version: 24
        cache: 'npm'
        cache-dependency-path: 'web/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
