name: sqlc-diff
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: sqlc-dev/setup-sqlc@v5
        with:
          sqlc-version: "1.31.1"
      - run: sqlc diff
        working-directory: "api/internal/db"
