name: sqlc-diff
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: "1.29.0"
      - run: sqlc diff
        working-directory: "api/internal/db"
